##
# Publish new action tag(s) for downstream consumption
##
name: Publish

# Manual or automatic release
on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Release with semantic tag like v1.0.3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
          token: ${{ secrets.MOD_PAT }}
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install deps and build
        run: npm ci && npm run build
            
      # Compile dist/index.js and bundle with action.yml
      # Force push major and minor tags, e.g. v1, v1.0
      # See documentation: https://github.com/JasonEtco/build-and-tag-action
      - name: Build and tag
        uses: JasonEtco/build-and-tag-action@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.MOD_PAT }}
